language: php # to have .travis installing the php version we indicate
sudo: false

php:
    - 5.6
cache:
    directories:
        - $HOME/.gradle
        - $HOME/pg

before_install:
    - git clone --depth 1 git://github.com/thehyve/transmart-travis.git ~/ts-travis
    - source ~/ts-travis/postgresql_cluster.sh
    - source ~/ts-travis/init.sh

install:
    - install_pg 9.4.4
    - create_cluster

before_script:
    - start_cluster
    - checkout_project_branch_with_fallback transmart/transmart-data master ~/transmart-data
    - cd ~/transmart-data
    - make -C env ../vars
    # put tablespaces somewhere we can write instead
    - echo TABLESPACES=~/tablespaces/ >> vars
    - echo PGSQL_BIN=$HOME/pg/bin/ >> vars
    - echo PGPORT=5433 >> vars
    - echo PGUSER=travis >> vars
    - source vars
    - ~/pg/bin/psql -c "ALTER USER travis PASSWORD 'travis'" -d template1
    - mkdir -p $TABLESPACES/{biomart,deapp,indx,search_app,transmart}
    - PGDATABASE=template1 make -C ddl/postgres/GLOBAL tablespaces
    - skip_fix_tablespaces=1 make -j3 postgres > /dev/null
    - cd -
    - cp .batchdb-travis.properties batchdb.properties
    - ./gradlew --console plain functionalTestPrepare

script:
    - ./gradlew --info --console plain clean
    - ./gradlew --info --console plain check
    - ./gradlew --info --console plain functionalTest
    - ./gradlew --console plain capsule

after_success:
    - ./.travis_upload
