language: php # to have .travis installing the php version we indicate
sudo: false
php:
    - 5.6
cache:
    directories:
        - $HOME/.gradle
        - $HOME/pg

before_install:
    - git clone --depth 1 git://github.com/thehyve/transmart-travis.git ~/ts-travis
    - source ~/ts-travis/init.sh
    - source ~/ts-travis/postgresql_cluster.sh

install:
    - wget -O - http://files.thehyve.net/json-perl.tar.gz | tar -C ~ -xzf -
    - export PERL5LIB=$HOME/perl5/lib/perl5
    - install_pg 9.4.4
    - create_cluster

before_script:
    - start_cluster
    # never try thehyve's repos' master
    - test $(travis_get_owner) = thehyve -a $(get_branch) = master || maybe_checkout_project_branch $(travis_get_owner)/transmart-data || test $? -ne 1
    - test -d ~/transmart-data || maybe_checkout_project_branch transmart/transmart-data || test $? -ne 1
    - test -d ~/transmart-data || git clone --depth 1 https://github.com/transmart/transmart-data.git ~/transmart-data
    - cd ~/transmart-data
    - make -C env ../vars
    # put tablespaces somewhere we can write instead
    - echo TABLESPACES=~/tablespaces/ >> vars
    - echo PGSQL_BIN=$HOME/pg/bin/ >> vars
    - echo PGPORT=5433 >> vars
    - echo PGUSER=travis >> vars
    - source vars
    - ~/pg/bin/psql -c "ALTER USER travis PASSWORD 'travis'" -d template1
    - mkdir -p $TABLESPACES/{biomart,deapp,indx,search_app,transmart}
    - PGDATABASE=template1 make -C ddl/postgres/GLOBAL tablespaces
    - skip_fix_tablespaces=1 make -j3 postgres > /dev/null
    - cd -
    - cp .batchdb-travis.properties batchdb.properties
    - ./gradlew --console plain functionalTestPrepare

script:
    - ./gradlew --info --console plain clean
    - ./gradlew --info --console plain check
    - ./gradlew --info --console plain functionalTest
    - ./gradlew --console plain capsule

after_success:
    - ./.travis_upload
